name: lorenzscore
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - scipy>=1.13
  - matplotlib>=3.7
  - tqdm>=4.66
  - pip
  - pip:
      - torch>=2.2
      - torchdiffeq>=0.2.5
      - tensorboardX>=2.6
